version: 0.1

env:
  variables:
    SERVICES: "dynamodb"

phases:
  install:
    commands:
      - curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
      - pip install localstack
  build:
    commands:
      - docker-compose --version
      - localstack start --docker
      - aws --endpoint-url http://localhost:4569 dynamodb list-tables
