version: 0.2

env:
  variables:
    DOCKER_COMPOSE_VERSION: "1.18.0"
 
phases:
  install:
    commands:
      - sudo apt-get update
      - python -m venv .
      - . bin/activate
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
  pre_build:
    commands:
      - pip install -r requirements.txt
      - docker-compose up -d
  build:
    commands:
      - LOCAL_DEBUG=true DYNAMODB_ENDPOINT=http://localstack:4569 python test.py
