version: 0.1

env:
  variables:
    SERVICES: "dynamodb"

phases:
  install:
    commands:
      - pip install pipenv      
  build:
    commands:
      - pipenv install
      - pipenv run python -m unittest
